services:
  - type: web
    name: yt-audio-api
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT main:app --timeout 120
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
